#!/bin/bash

case $1 in
	start)
		/tmp/sleepwalkingserver &
		;;
	stop)
		kill $(cat /tmp/sleepwalkingserver.pid)
		;;
        *)
		echo "usage sleepwalkingserver start|stop"
		exit 1
		;;
esac

exit 0
